-- ==========================================
-- SCRIPT DE CONFIGURACIÓN SUPABASE - CASINO SSOO
-- ==========================================
-- Instrucciones:
-- Copia todo este código y pégalo en el SQL Editor de tu panel de Supabase.
-- Luego haz clic en "Run" (Ejecutar) para crear todas las tablas, buckets y políticas.

-- 1. Crear Tablas

-- Tabla de Usuarios (Socios)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    jerarquia text,
    "nombreApellido" text NOT NULL,
    dni text NOT NULL UNIQUE,
    ce text NOT NULL,
    "fechaNacimiento" date,
    edad integer,
    telefono text,
    "fechaRegistro" timestamp with time zone DEFAULT timezone('utc'::text, now()),
    ultimo_acceso timestamp with time zone
);

-- Tabla de Planilla Mensual
CREATE TABLE IF NOT EXISTS public.planilla_mensual (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    socio text NOT NULL,
    jerarquia text,
    "Ene" numeric DEFAULT 0,
    "Feb" numeric DEFAULT 0,
    "Mar" numeric DEFAULT 0,
    "Abr" numeric DEFAULT 0,
    "May" numeric DEFAULT 0,
    "Jun" numeric DEFAULT 0,
    "Jul" numeric DEFAULT 0,
    "Ago" numeric DEFAULT 0,
    "Sep" numeric DEFAULT 0,
    "Oct" numeric DEFAULT 0,
    "Nov" numeric DEFAULT 0,
    "Dic" numeric DEFAULT 0
);

-- Tabla de Propuestas
CREATE TABLE IF NOT EXISTS public.propuestas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mi text,
    ce text,
    propuesta text NOT NULL,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now()),
    jerarquia text,
    nombre text,
    votos jsonb DEFAULT '[]'::jsonb
);

-- Tabla de Balance
CREATE TABLE IF NOT EXISTS public.balance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto text NOT NULL,
    haber numeric DEFAULT 0,
    debe numeric DEFAULT 0,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Tabla de Galería
CREATE TABLE IF NOT EXISTS public.galeria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion text,
    url text NOT NULL,
    "fileName" text NOT NULL,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Tabla de Documentación
CREATE TABLE IF NOT EXISTS public.documentacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL,
    url text NOT NULL,
    "fileName" text NOT NULL,
    fecha timestamp with time zone DEFAULT timezone('utc'::text, now())
);


-- 2. Habilitar RLS (Seguridad a Nivel de Filas)
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planilla_mensual ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.propuestas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.balance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galeria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documentacion ENABLE ROW LEVEL SECURITY;


-- 3. Crear Políticas de Acceso (Acceso total para la app interna)
-- Permitir todas las operaciones de inserción, actualización, eliminación y lectura de forma anónima
-- Dado que la app maneja su propio login, liberamos las tablas a nivel de API para que funcionen con la key anónima.

-- Usuarios
CREATE POLICY "Permitir acceso total a usuarios" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);

-- Planilla Mensual
CREATE POLICY "Permitir acceso total a planilla" ON public.planilla_mensual FOR ALL USING (true) WITH CHECK (true);

-- Propuestas
CREATE POLICY "Permitir acceso total a propuestas" ON public.propuestas FOR ALL USING (true) WITH CHECK (true);

-- Balance
CREATE POLICY "Permitir acceso total a balance" ON public.balance FOR ALL USING (true) WITH CHECK (true);

-- Galería
CREATE POLICY "Permitir acceso total a galeria" ON public.galeria FOR ALL USING (true) WITH CHECK (true);

-- Documentación
CREATE POLICY "Permitir acceso total a documentacion" ON public.documentacion FOR ALL USING (true) WITH CHECK (true);


-- 4. Crear Storage Buckets para archivos

-- Crear el bucket de galeria si no existe
INSERT INTO storage.buckets (id, name, public) 
VALUES ('galeria', 'galeria', true) 
ON CONFLICT (id) DO NOTHING;

-- Crear el bucket de documentacion si no existe
INSERT INTO storage.buckets (id, name, public) 
VALUES ('documentacion', 'documentacion', true) 
ON CONFLICT (id) DO NOTHING;

-- Habilitar RLS en objetos de Storage (Omitido por restricción de permisos, normalmente ya está activo)
-- ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- 5. Crear políticas de acceso para los Buckets
-- Políticas para el bucket 'galeria'
CREATE POLICY "Acceso publico total a galeria" ON storage.objects FOR ALL 
USING (bucket_id = 'galeria') 
WITH CHECK (bucket_id = 'galeria');

-- Políticas para el bucket 'documentacion'
CREATE POLICY "Acceso publico total a documentacion" ON storage.objects FOR ALL 
USING (bucket_id = 'documentacion') 
WITH CHECK (bucket_id = 'documentacion');

-- ==========================================
-- FIN DEL SCRIPT
-- ==========================================
